version: '2'
services:

    rstudio:
      image: rocker/tidyverse:latest
      container_name: rstudio
      environment:
        - PASSWORD=pw
      volumes:
        - .:/home/rstudio/project
      ports:
        - "8787:8787"
